### ISSUE TITLE
Alfresco generator no longer works after update

### ISSUE THREAD

**Issue by yregaieg** [binduwavell/generator-alfresco#155]
I recently tried to update alfresco-generator before starting a new project and that sound like it broke my install. I also tried to remove and then reinstall the module but that does not seem to solve my problem.

Here is the output I am getting :
```
yregaieg@younes-laptop:/work$ yo alfresco
/usr/lib/node_modules/generator-alfresco/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/generator-alfresco/node_modules/deasync/build/deasync.node
 → /usr/lib/node_modules/generator-alfresco/node_modules/deasync/build/Debug/deasync.node
 → /usr/lib/node_modules/generator-alfresco/node_modules/deasync/build/Release/deasync.node
 → /usr/lib/node_modules/generator-alfresco/node_modules/deasync/out/Debug/deasync.node
 → /usr/lib/node_modules/generator-alfresco/node_modules/deasync/Debug/deasync.node
 → /usr/lib/node_modules/generator-alfresco/node_modules/deasync/out/Release/deasync.node
 → /usr/lib/node_modules/generator-alfresco/node_modules/deasync/Release/deasync.node
 → /usr/lib/node_modules/generator-alfresco/node_modules/deasync/build/default/deasync.node
 → /usr/lib/node_modules/generator-alfresco/node_modules/deasync/compiled/7.4.0/linux/x64/deasync.node
    at bindings (/usr/lib/node_modules/generator-alfresco/node_modules/bindings/bindings.js:88:9)
    at /usr/lib/node_modules/generator-alfresco/node_modules/deasync/index.js:34:32
    at Object.<anonymous> (/usr/lib/node_modules/generator-alfresco/node_modules/deasync/index.js:76:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

And for your information, when I try to lookup the missing dependency, I get this output : 

```
yregaieg@younes-laptop:~$ find -name "deasync.node" 
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/build/Release/obj.target/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/win32-ia32-node-5/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/linux-ia32-node-0.10/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/darwin-x64-node-0.11/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/darwin-x64-node-5/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/linux-x64-node-0.10/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/win32-x64-node-6/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/linux-ia32-node-4/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/win32-x64-node-0.11/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/win32-ia32-node-6/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/linux-ia32-node-0.12/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/linux-ia32-node-0.11/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/win32-x64-node-5/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/linux-x64-node-6/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/darwin-x64-node-4/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/win32-ia32-node-0.10/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/linux-x64-node-5/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/darwin-x64-node-6/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/linux-x64-node-0.12/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/linux-x64-node-4/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/win32-x64-node-4/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/darwin-x64-node-0.10/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/win32-x64-node-0.12/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/linux-ia32-node-6/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/linux-x64-node-0.11/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/win32-ia32-node-4/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/win32-x64-node-0.10/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/darwin-x64-node-0.12/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/win32-ia32-node-0.12/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/win32-ia32-node-0.11/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/linux-ia32-node-5/deasync.node
./.nvm/versions/node/v7.4.0/lib/node_modules/generator-alfresco/node_modules/deasync/bin/linux-x64-node-7/deasync.node
```

**Comment by binduwavell** [comment]
Unfortunately we don’t support Node 7 right now. We are in a bit of a bind, I wanted to support back to node 0.10 as that is the version in the default apt repository for versions of ubuntu on the supported platforms list. However, we are now running into issues where versions of our dependencies either work with 0.10 or 7 but not both. In some cases we don’t have a good alternative for replacing our dependency.

I documented some of this stuff here: https://github.com/binduwavell/generator-alfresco/wiki/Supported-Platforms-Node-Versions . I also have this issue for us to address this situation: https://github.com/binduwavell/generator-alfresco/issues/153 . I’d be very interested in your opinions about support for Node 7 vs Node 0.10.
