### ISSUE TITLE
webscript: validate is not called when options are passed from command line

### ISSUE THREAD

**Issue by vprince1** [binduwavell/generator-alfresco#40]
I think the below problem is not specific to webscript sub-generator.. I found this issue when I was testing my model sub-generator. I think we should handle this in a common manner rather than calling a 'validate' in every 'when' function.

```
> yo alfresco:webscript -i -p
     _-----_
    |       |    .--------------------------.
    |--(o)--|    |  Adding webscript to boo |
   `---------´   |         project!         |
    ( _´U`_ )    '--------------------------'
    /___A___\
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? Which type of module would you like to add a webscript to? repo
INFO:  Using only available source module: org.alfresco:repo-amp:1.0.0-SNAPSHOT:amp:repo:source
INFO:  Using webscript id from command line: true


readline.js:925
            throw err;
            ^

TypeError: pkg.replace is not a function
    at packageFilter (/Users/vijayprince/Work/projects/generator-alfresco/generators/webscript/index.js:933:20)
    at null.<anonymous> (/Users/vijayprince/Work/projects/generator-alfresco/generators/webscript/index.js:70:19)
    at module.exports (/usr/local/lib/node_modules/yo/node_modules/run-async/index.js:15:21)
    at AnonymousObservable.__subscribe (/usr/local/lib/node_modules/yo/node_modules/inquirer/lib/ui/prompt.js:121:7)
    at AnonymousObservable.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:63:31)
    at setDisposable (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:5741:44)
    at AnonymousObservable.innerSubscribe [as _subscribe] (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:5755:9)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:1604:19)
    at AnonymousObservable.__subscribe (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:2112:21)
    at AnonymousObservable.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:63:31)
    at setDisposable (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:5741:44)
    at AnonymousObservable.innerSubscribe [as _subscribe] (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:5755:9)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:1604:19)
    at MergeObserver.handleSubscribe (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:2910:28)
    at MergeObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:2916:16)
    at MergeObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:63:31)
```

**Comment by binduwavell** [comment]
Thanks for reporting this Vijay. I'm not sure what's going on, I thought no all the base for matters handle true which is the value you get if you provide a flag without a value. Maybe this is one formatted that is doing it's own thing and not handling true properly. As you know, I'm on vacation so may not be able to look at this until Minday evening. If you have further insights or specific suggestions about how to not use when functions I'm very interested in your ideas?

**Comment by binduwavell** [comment]
Sorry about the autocorrect in the last comment. I thought all the common prompt filters handled true properly. 

If you provide an option with no value you get the Boolean true value from yeoman.

Possibly this question/prompt is not using one of those filters or I messed something up in one of those filters. At least they have tests so should be easy to see what's going on with the common prompt filters or to add a handler for true in the custom filter.

**Comment by binduwavell** [comment]
Got to the code from my phone it's not using a common filter. A bunch of the custom filters are not checking for true. I'll fix. Still want to know what your thoughts are about not having all of this in the when function...

**Comment by binduwavell** [comment]
Fixed the reported issue so closing this. Let's talk about options for simplifying the prompt process next week.
